# Generated by Django 4.0.4 on 2022-04-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turiviusapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='icmscalculator',
            name='product',
            field=models.CharField(default='', max_length=100),
        ),
    ]
