# Generated by Django 4.0.4 on 2022-05-03 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turiviusapi', '0004_taxcalculator_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='product',
            name='taxed_value',
        ),
    ]
