# Generated by Django 4.0.4 on 2022-05-03 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turiviusapi', '0005_remove_product_tax_remove_product_taxed_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
    ]
