# Generated by Django 4.0.4 on 2022-05-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turiviusapi', '0006_rename_product_name_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Value'),
        ),
    ]
